import Head from "next/head";
import AuthForm from "../components/auth/AuthForm";
import { IsLoginContextProvider } from "../context/IsLoginProvider";
import { getSession } from "next-auth/react";

export default function Auth() {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IsLoginContextProvider>
        <AuthForm />
      </IsLoginContextProvider>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getSession({ req: context.req });

  if (session) {
    return {
      redirect: {
        destination: "/",
        permament: false,
      },
    };
  }

  return {
    props: { session },
  };
}
