import Head from "next/head";
import AuthForm from "../components/auth/AuthForm";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome to Journal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
}
